// AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
// Regenerated by scripts/generate-registry.mjs on every "npm run dev" / "npm run build".
// Lazily code-splits each tool's UI so heavy libraries only ship to the pages that need them.
// A tool with a meta.ts but no index.tsx yet is intentionally omitted here — its SEO page
// still renders (via TOOL_REGISTRY) and falls back to a "coming soon" state.
// eslint-disable
"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import { ToolLoadingState } from "@/components/tools/ToolLoadingState";

export const TOOL_COMPONENTS: Record<string, ComponentType> = {
  "age-calculator": dynamic(() => import("@/tools/calculator/age-calculator"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "bmi-calculator": dynamic(() => import("@/tools/calculator/bmi-calculator"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "percentage-calculator": dynamic(() => import("@/tools/calculator/percentage-calculator"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "base64-encoder": dynamic(() => import("@/tools/developer/base64-encoder"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "json-formatter": dynamic(() => import("@/tools/developer/json-formatter"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "background-removeimage": dynamic(() => import("@/tools/image/background-removeimage"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "compress-image": dynamic(() => import("@/tools/image/compress-image"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "convert-to-webp": dynamic(() => import("@/tools/image/convert-to-webp"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "jpg-to-png": dynamic(() => import("@/tools/image/jpg-to-png"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "resize-image": dynamic(() => import("@/tools/image/resize-image"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "compress-pdf": dynamic(() => import("@/tools/pdf/compress-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "delete-pdf-pages": dynamic(() => import("@/tools/pdf/delete-pdf-pages"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "extract-pdf-pages": dynamic(() => import("@/tools/pdf/extract-pdf-pages"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "images-to-pdf": dynamic(() => import("@/tools/pdf/images-to-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "merge-pdf": dynamic(() => import("@/tools/pdf/merge-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "pdf-ocr": dynamic(() => import("@/tools/pdf/pdf-ocr"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "pdf-page-numbers": dynamic(() => import("@/tools/pdf/pdf-page-numbers"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "pdf-to-jpg": dynamic(() => import("@/tools/pdf/pdf-to-jpg"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "pdf-to-word": dynamic(() => import("@/tools/pdf/pdf-to-word"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "rotate-pdf": dynamic(() => import("@/tools/pdf/rotate-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "split-pdf": dynamic(() => import("@/tools/pdf/split-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "word-to-pdf": dynamic(() => import("@/tools/pdf/word-to-pdf"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "case-converter": dynamic(() => import("@/tools/text/case-converter"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "character-counter": dynamic(() => import("@/tools/text/character-counter"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "remove-duplicate-lines": dynamic(() => import("@/tools/text/remove-duplicate-lines"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "word-counter": dynamic(() => import("@/tools/text/word-counter"), { ssr: false, loading: () => <ToolLoadingState /> }),
  "word-formatter": dynamic(() => import("@/tools/word/word-formatter"), { ssr: false, loading: () => <ToolLoadingState /> }),
};
