// AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
// Regenerated by scripts/generate-registry.mjs on every "npm run dev" / "npm run build".
// Source of truth: tools/<category>/<slug>/meta.ts
// eslint-disable

import type { ToolMeta } from "@/types";

import ageCalculator from "@/tools/calculator/age-calculator/meta";
import bmiCalculator from "@/tools/calculator/bmi-calculator/meta";
import percentageCalculator from "@/tools/calculator/percentage-calculator/meta";
import base64Encoder from "@/tools/developer/base64-encoder/meta";
import jsonFormatter from "@/tools/developer/json-formatter/meta";
import backgroundRemoveImage from "@/tools/image/background-remove-image/meta";
import compressImage from "@/tools/image/compress-image/meta";
import convertToWebp from "@/tools/image/convert-to-webp/meta";
import resizeImage from "@/tools/image/resize-image/meta";
import compressPdf from "@/tools/pdf/compress-pdf/meta";
import deletePdfPages from "@/tools/pdf/delete-pdf-pages/meta";
import imagesToPdf from "@/tools/pdf/images-to-pdf/meta";
import mergePdf from "@/tools/pdf/merge-pdf/meta";
import pdfOcr from "@/tools/pdf/pdf-ocr/meta";
import pdfToJpg from "@/tools/pdf/pdf-to-jpg/meta";
import pdfToWord from "@/tools/pdf/pdf-to-word/meta";
import protectpdf from "@/tools/pdf/protectpdf/meta";
import rotatePdf from "@/tools/pdf/rotate-pdf/meta";
import splitPdf from "@/tools/pdf/split-pdf/meta";
import unlockpdf from "@/tools/pdf/unlockpdf/meta";
import wordToPdf from "@/tools/pdf/word-to-pdf/meta";
import caseConverter from "@/tools/text/case-converter/meta";
import characterCounter from "@/tools/text/character-counter/meta";
import wordCounter from "@/tools/text/word-counter/meta";
import jpgToPdf from "@/tools/image/jpg-to-png/meta";

export const TOOL_REGISTRY: ToolMeta[] = [
  ageCalculator,
  bmiCalculator,
  percentageCalculator,
  base64Encoder,
  jsonFormatter,
  backgroundRemoveImage,
  compressImage,
  convertToWebp,
  resizeImage,
  compressPdf,
  deletePdfPages,
  imagesToPdf,
  mergePdf,
  pdfOcr,
  pdfToJpg,
  pdfToWord,
  protectpdf,
  rotatePdf,
  splitPdf,
  unlockpdf,
  wordToPdf,
  caseConverter,
  characterCounter,
  wordCounter,
  jpgToPdf,
];
