export const metadata = {
  title: "Disclaimer | MugoX",
  description:
    "Read the disclaimer for using MugoX online tools and services.",
};

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="text-4xl font-bold mb-6">Disclaimer</h1>

      <p className="text-gray-600 mb-8">
        Last updated: July 2026
      </p>

      <div className="space-y-8 text-gray-700 leading-8">

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            General Information
          </h2>

          <p>
            MugoX provides free online tools for educational, informational,
            and productivity purposes. While we strive to keep every tool
            accurate and reliable, we do not guarantee that all results will
            always be complete, error-free, or suitable for every situation.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            No Professional Advice
          </h2>

          <p>
            The information and results generated by our tools should not be
            considered legal, financial, medical, tax, engineering, or other
            professional advice. Please consult a qualified professional before
            making important decisions.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            Tool Accuracy
          </h2>

          <p>
            Although we regularly improve our tools, MugoX cannot guarantee the
            accuracy, completeness, or reliability of every generated result.
            Users are responsible for reviewing and verifying all outputs before
            relying on them.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            Third-Party Content
          </h2>

          <p>
            Some pages may contain links to third-party websites or services.
            MugoX is not responsible for the content, privacy practices, or
            availability of those external websites.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            Limitation of Liability
          </h2>

          <p>
            MugoX and its owners shall not be held liable for any direct,
            indirect, incidental, or consequential damages resulting from the
            use or inability to use our website or tools.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-3">
            Contact
          </h2>

          <p>
            If you have any questions regarding this Disclaimer, please contact
            us at:
          </p>

          <p className="mt-2 font-medium">
            <a
              href="mailto:mymugox@gmail.com"
              className="text-blue-600 hover:underline"
            >
              mymugox@gmail.com
            </a>
          </p>
        </section>

      </div>
    </main>
  );
}